; ModuleID = 'circuit-154'
source_filename = "circuit-154"

%Qubit = type opaque
%Result = type opaque

define void @circuit-154() #0 {
entry:
  call void @__quantum__rt__initialize(i8* null)
  call void @__quantum__qis__h__body(%Qubit* null)
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__mz__body(%Qubit* null, %Result* null)
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Result* inttoptr (i64 1 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Result* inttoptr (i64 2 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Result* inttoptr (i64 3 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Result* inttoptr (i64 4 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Result* inttoptr (i64 5 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Result* inttoptr (i64 6 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Result* inttoptr (i64 7 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Result* inttoptr (i64 8 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Result* inttoptr (i64 9 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Result* inttoptr (i64 10 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Result* inttoptr (i64 11 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Result* inttoptr (i64 12 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Result* inttoptr (i64 13 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Result* inttoptr (i64 14 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Result* inttoptr (i64 15 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Result* inttoptr (i64 16 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Result* inttoptr (i64 17 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Result* inttoptr (i64 18 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Result* inttoptr (i64 19 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Result* inttoptr (i64 20 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Result* inttoptr (i64 21 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Result* inttoptr (i64 22 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Result* inttoptr (i64 23 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Result* inttoptr (i64 24 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Result* inttoptr (i64 25 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Result* inttoptr (i64 26 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 27 to %Qubit*), %Result* inttoptr (i64 27 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 28 to %Qubit*), %Result* inttoptr (i64 28 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 29 to %Qubit*), %Result* inttoptr (i64 29 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 30 to %Qubit*), %Result* inttoptr (i64 30 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 31 to %Qubit*), %Result* inttoptr (i64 31 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 32 to %Qubit*), %Result* inttoptr (i64 32 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 33 to %Qubit*), %Result* inttoptr (i64 33 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Result* inttoptr (i64 34 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Result* inttoptr (i64 35 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Result* inttoptr (i64 36 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Result* inttoptr (i64 37 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Result* inttoptr (i64 38 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Result* inttoptr (i64 39 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Result* inttoptr (i64 40 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Result* inttoptr (i64 41 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Result* inttoptr (i64 42 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Result* inttoptr (i64 43 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Result* inttoptr (i64 44 to %Result*))
  call void @__quantum__rt__array_record_output(i64 45, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 44 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 43 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 42 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 41 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 40 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 39 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 38 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 37 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 36 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 35 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 34 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 33 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 32 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 31 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 30 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 29 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 28 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 27 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 26 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 25 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 24 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 23 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 22 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 21 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 20 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 19 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 18 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 17 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 16 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 15 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 14 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 13 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 12 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 11 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 10 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 9 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 8 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 7 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 6 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 5 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 4 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 3 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 2 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 1 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* null, i8* null)
  ret void
}

declare void @__quantum__rt__initialize(i8*)

declare void @__quantum__qis__h__body(%Qubit*)

declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__mz__body(%Qubit*, %Result* writeonly) #1

declare void @__quantum__rt__array_record_output(i64, i8*)

declare void @__quantum__rt__result_record_output(%Result*, i8*)

attributes #0 = { "entry_point" "output_labeling_schema" "qir_profiles"="custom" "required_num_qubits"="45" "required_num_results"="45" }
attributes #1 = { "irreversible" }

!llvm.module.flags = !{!0, !1, !2, !3}

!0 = !{i32 1, !"qir_major_version", i32 1}
!1 = !{i32 7, !"qir_minor_version", i32 0}
!2 = !{i32 1, !"dynamic_qubit_management", i1 false}
!3 = !{i32 1, !"dynamic_result_management", i1 false}
