; ModuleID = 'circuit-161'
source_filename = "circuit-161"

%Qubit = type opaque
%Result = type opaque

define void @circuit-161() #0 {
entry:
  call void @__quantum__rt__initialize(i8* null)
  call void @__quantum__qis__h__body(%Qubit* null)
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 67 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 68 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 69 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 70 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 71 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 72 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 73 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 74 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 75 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 76 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 77 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 78 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 79 to %Qubit*))
  call void @__quantum__qis__mz__body(%Qubit* null, %Result* null)
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Result* inttoptr (i64 1 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Result* inttoptr (i64 2 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Result* inttoptr (i64 3 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Result* inttoptr (i64 4 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Result* inttoptr (i64 5 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Result* inttoptr (i64 6 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Result* inttoptr (i64 7 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Result* inttoptr (i64 8 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Result* inttoptr (i64 9 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Result* inttoptr (i64 10 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Result* inttoptr (i64 11 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Result* inttoptr (i64 12 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Result* inttoptr (i64 13 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Result* inttoptr (i64 14 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Result* inttoptr (i64 15 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Result* inttoptr (i64 16 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Result* inttoptr (i64 17 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Result* inttoptr (i64 18 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Result* inttoptr (i64 19 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Result* inttoptr (i64 20 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Result* inttoptr (i64 21 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Result* inttoptr (i64 22 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Result* inttoptr (i64 23 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Result* inttoptr (i64 24 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Result* inttoptr (i64 25 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Result* inttoptr (i64 26 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 27 to %Qubit*), %Result* inttoptr (i64 27 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 28 to %Qubit*), %Result* inttoptr (i64 28 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 29 to %Qubit*), %Result* inttoptr (i64 29 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 30 to %Qubit*), %Result* inttoptr (i64 30 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 31 to %Qubit*), %Result* inttoptr (i64 31 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 32 to %Qubit*), %Result* inttoptr (i64 32 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 33 to %Qubit*), %Result* inttoptr (i64 33 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Result* inttoptr (i64 34 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Result* inttoptr (i64 35 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Result* inttoptr (i64 36 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Result* inttoptr (i64 37 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Result* inttoptr (i64 38 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Result* inttoptr (i64 39 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Result* inttoptr (i64 40 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Result* inttoptr (i64 41 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Result* inttoptr (i64 42 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Result* inttoptr (i64 43 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Result* inttoptr (i64 44 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 45 to %Qubit*), %Result* inttoptr (i64 45 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 46 to %Qubit*), %Result* inttoptr (i64 46 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 47 to %Qubit*), %Result* inttoptr (i64 47 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 48 to %Qubit*), %Result* inttoptr (i64 48 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 49 to %Qubit*), %Result* inttoptr (i64 49 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 50 to %Qubit*), %Result* inttoptr (i64 50 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 51 to %Qubit*), %Result* inttoptr (i64 51 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 52 to %Qubit*), %Result* inttoptr (i64 52 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 53 to %Qubit*), %Result* inttoptr (i64 53 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 54 to %Qubit*), %Result* inttoptr (i64 54 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 55 to %Qubit*), %Result* inttoptr (i64 55 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 56 to %Qubit*), %Result* inttoptr (i64 56 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 57 to %Qubit*), %Result* inttoptr (i64 57 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 58 to %Qubit*), %Result* inttoptr (i64 58 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 59 to %Qubit*), %Result* inttoptr (i64 59 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 60 to %Qubit*), %Result* inttoptr (i64 60 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 61 to %Qubit*), %Result* inttoptr (i64 61 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 62 to %Qubit*), %Result* inttoptr (i64 62 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 63 to %Qubit*), %Result* inttoptr (i64 63 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 64 to %Qubit*), %Result* inttoptr (i64 64 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 65 to %Qubit*), %Result* inttoptr (i64 65 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 66 to %Qubit*), %Result* inttoptr (i64 66 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 67 to %Qubit*), %Result* inttoptr (i64 67 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 68 to %Qubit*), %Result* inttoptr (i64 68 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 69 to %Qubit*), %Result* inttoptr (i64 69 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 70 to %Qubit*), %Result* inttoptr (i64 70 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 71 to %Qubit*), %Result* inttoptr (i64 71 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 72 to %Qubit*), %Result* inttoptr (i64 72 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 73 to %Qubit*), %Result* inttoptr (i64 73 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 74 to %Qubit*), %Result* inttoptr (i64 74 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 75 to %Qubit*), %Result* inttoptr (i64 75 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 76 to %Qubit*), %Result* inttoptr (i64 76 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 77 to %Qubit*), %Result* inttoptr (i64 77 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 78 to %Qubit*), %Result* inttoptr (i64 78 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 79 to %Qubit*), %Result* inttoptr (i64 79 to %Result*))
  call void @__quantum__rt__array_record_output(i64 80, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 79 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 78 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 77 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 76 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 75 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 74 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 73 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 72 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 71 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 70 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 69 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 68 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 67 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 66 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 65 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 64 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 63 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 62 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 61 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 60 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 59 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 58 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 57 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 56 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 55 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 54 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 53 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 52 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 51 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 50 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 49 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 48 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 47 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 46 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 45 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 44 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 43 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 42 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 41 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 40 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 39 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 38 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 37 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 36 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 35 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 34 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 33 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 32 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 31 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 30 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 29 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 28 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 27 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 26 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 25 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 24 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 23 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 22 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 21 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 20 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 19 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 18 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 17 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 16 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 15 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 14 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 13 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 12 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 11 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 10 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 9 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 8 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 7 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 6 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 5 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 4 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 3 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 2 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 1 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* null, i8* null)
  ret void
}

declare void @__quantum__rt__initialize(i8*)

declare void @__quantum__qis__h__body(%Qubit*)

declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__mz__body(%Qubit*, %Result* writeonly) #1

declare void @__quantum__rt__array_record_output(i64, i8*)

declare void @__quantum__rt__result_record_output(%Result*, i8*)

attributes #0 = { "entry_point" "output_labeling_schema" "qir_profiles"="custom" "required_num_qubits"="80" "required_num_results"="80" }
attributes #1 = { "irreversible" }

!llvm.module.flags = !{!0, !1, !2, !3}

!0 = !{i32 1, !"qir_major_version", i32 1}
!1 = !{i32 7, !"qir_minor_version", i32 0}
!2 = !{i32 1, !"dynamic_qubit_management", i1 false}
!3 = !{i32 1, !"dynamic_result_management", i1 false}
