module @run_ghz {
  func.func public @jit_run_ghz() -> (tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>) attributes {llvm.emit_c_interface} {
    %0:65 = catalyst.launch_kernel @module_ghz::@ghz() : () -> (tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>)
    return %0#0, %0#1, %0#2, %0#3, %0#4, %0#5, %0#6, %0#7, %0#8, %0#9, %0#10, %0#11, %0#12, %0#13, %0#14, %0#15, %0#16, %0#17, %0#18, %0#19, %0#20, %0#21, %0#22, %0#23, %0#24, %0#25, %0#26, %0#27, %0#28, %0#29, %0#30, %0#31, %0#32, %0#33, %0#34, %0#35, %0#36, %0#37, %0#38, %0#39, %0#40, %0#41, %0#42, %0#43, %0#44, %0#45, %0#46, %0#47, %0#48, %0#49, %0#50, %0#51, %0#52, %0#53, %0#54, %0#55, %0#56, %0#57, %0#58, %0#59, %0#60, %0#61, %0#62, %0#63, %0#64 : tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>
  }
  module @module_ghz {
    module attributes {transform.with_named_sequence} {
      transform.named_sequence @__transform_main(%arg0: !transform.op<"builtin.module">) {
        transform.yield 
      }
    }
    func.func public @ghz() -> (tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>) attributes {diff_method = "parameter-shift", llvm.linkage = #llvm.linkage<internal>, qnode} {
      %c0_i64 = arith.constant 0 : i64
      quantum.device shots(%c0_i64) ["/home/kew/.venv/lib/python3.10/site-packages/pennylane_lightning/liblightning_qubit_catalyst.so", "LightningSimulator", "{'mcmc': False, 'num_burnin': 0, 'kernel_name': None}"]
      %0 = quantum.alloc( 65) : !quantum.reg
      %1 = quantum.extract %0[ 0] : !quantum.reg -> !quantum.bit
      %out_qubits = quantum.custom "Hadamard"() %1 : !quantum.bit
      %2 = quantum.extract %0[ 1] : !quantum.reg -> !quantum.bit
      %out_qubits_0:2 = quantum.custom "CNOT"() %out_qubits, %2 : !quantum.bit, !quantum.bit
      %3 = quantum.extract %0[ 2] : !quantum.reg -> !quantum.bit
      %out_qubits_1:2 = quantum.custom "CNOT"() %out_qubits_0#0, %3 : !quantum.bit, !quantum.bit
      %4 = quantum.extract %0[ 3] : !quantum.reg -> !quantum.bit
      %out_qubits_2:2 = quantum.custom "CNOT"() %out_qubits_1#0, %4 : !quantum.bit, !quantum.bit
      %5 = quantum.extract %0[ 4] : !quantum.reg -> !quantum.bit
      %out_qubits_3:2 = quantum.custom "CNOT"() %out_qubits_2#0, %5 : !quantum.bit, !quantum.bit
      %6 = quantum.extract %0[ 5] : !quantum.reg -> !quantum.bit
      %out_qubits_4:2 = quantum.custom "CNOT"() %out_qubits_3#0, %6 : !quantum.bit, !quantum.bit
      %7 = quantum.extract %0[ 6] : !quantum.reg -> !quantum.bit
      %out_qubits_5:2 = quantum.custom "CNOT"() %out_qubits_4#0, %7 : !quantum.bit, !quantum.bit
      %8 = quantum.extract %0[ 7] : !quantum.reg -> !quantum.bit
      %out_qubits_6:2 = quantum.custom "CNOT"() %out_qubits_5#0, %8 : !quantum.bit, !quantum.bit
      %9 = quantum.extract %0[ 8] : !quantum.reg -> !quantum.bit
      %out_qubits_7:2 = quantum.custom "CNOT"() %out_qubits_6#0, %9 : !quantum.bit, !quantum.bit
      %10 = quantum.extract %0[ 9] : !quantum.reg -> !quantum.bit
      %out_qubits_8:2 = quantum.custom "CNOT"() %out_qubits_7#0, %10 : !quantum.bit, !quantum.bit
      %11 = quantum.extract %0[ 10] : !quantum.reg -> !quantum.bit
      %out_qubits_9:2 = quantum.custom "CNOT"() %out_qubits_8#0, %11 : !quantum.bit, !quantum.bit
      %12 = quantum.extract %0[ 11] : !quantum.reg -> !quantum.bit
      %out_qubits_10:2 = quantum.custom "CNOT"() %out_qubits_9#0, %12 : !quantum.bit, !quantum.bit
      %13 = quantum.extract %0[ 12] : !quantum.reg -> !quantum.bit
      %out_qubits_11:2 = quantum.custom "CNOT"() %out_qubits_10#0, %13 : !quantum.bit, !quantum.bit
      %14 = quantum.extract %0[ 13] : !quantum.reg -> !quantum.bit
      %out_qubits_12:2 = quantum.custom "CNOT"() %out_qubits_11#0, %14 : !quantum.bit, !quantum.bit
      %15 = quantum.extract %0[ 14] : !quantum.reg -> !quantum.bit
      %out_qubits_13:2 = quantum.custom "CNOT"() %out_qubits_12#0, %15 : !quantum.bit, !quantum.bit
      %16 = quantum.extract %0[ 15] : !quantum.reg -> !quantum.bit
      %out_qubits_14:2 = quantum.custom "CNOT"() %out_qubits_13#0, %16 : !quantum.bit, !quantum.bit
      %17 = quantum.extract %0[ 16] : !quantum.reg -> !quantum.bit
      %out_qubits_15:2 = quantum.custom "CNOT"() %out_qubits_14#0, %17 : !quantum.bit, !quantum.bit
      %18 = quantum.extract %0[ 17] : !quantum.reg -> !quantum.bit
      %out_qubits_16:2 = quantum.custom "CNOT"() %out_qubits_15#0, %18 : !quantum.bit, !quantum.bit
      %19 = quantum.extract %0[ 18] : !quantum.reg -> !quantum.bit
      %out_qubits_17:2 = quantum.custom "CNOT"() %out_qubits_16#0, %19 : !quantum.bit, !quantum.bit
      %20 = quantum.extract %0[ 19] : !quantum.reg -> !quantum.bit
      %out_qubits_18:2 = quantum.custom "CNOT"() %out_qubits_17#0, %20 : !quantum.bit, !quantum.bit
      %21 = quantum.extract %0[ 20] : !quantum.reg -> !quantum.bit
      %out_qubits_19:2 = quantum.custom "CNOT"() %out_qubits_18#0, %21 : !quantum.bit, !quantum.bit
      %22 = quantum.extract %0[ 21] : !quantum.reg -> !quantum.bit
      %out_qubits_20:2 = quantum.custom "CNOT"() %out_qubits_19#0, %22 : !quantum.bit, !quantum.bit
      %23 = quantum.extract %0[ 22] : !quantum.reg -> !quantum.bit
      %out_qubits_21:2 = quantum.custom "CNOT"() %out_qubits_20#0, %23 : !quantum.bit, !quantum.bit
      %24 = quantum.extract %0[ 23] : !quantum.reg -> !quantum.bit
      %out_qubits_22:2 = quantum.custom "CNOT"() %out_qubits_21#0, %24 : !quantum.bit, !quantum.bit
      %25 = quantum.extract %0[ 24] : !quantum.reg -> !quantum.bit
      %out_qubits_23:2 = quantum.custom "CNOT"() %out_qubits_22#0, %25 : !quantum.bit, !quantum.bit
      %26 = quantum.extract %0[ 25] : !quantum.reg -> !quantum.bit
      %out_qubits_24:2 = quantum.custom "CNOT"() %out_qubits_23#0, %26 : !quantum.bit, !quantum.bit
      %27 = quantum.extract %0[ 26] : !quantum.reg -> !quantum.bit
      %out_qubits_25:2 = quantum.custom "CNOT"() %out_qubits_24#0, %27 : !quantum.bit, !quantum.bit
      %28 = quantum.extract %0[ 27] : !quantum.reg -> !quantum.bit
      %out_qubits_26:2 = quantum.custom "CNOT"() %out_qubits_25#0, %28 : !quantum.bit, !quantum.bit
      %29 = quantum.extract %0[ 28] : !quantum.reg -> !quantum.bit
      %out_qubits_27:2 = quantum.custom "CNOT"() %out_qubits_26#0, %29 : !quantum.bit, !quantum.bit
      %30 = quantum.extract %0[ 29] : !quantum.reg -> !quantum.bit
      %out_qubits_28:2 = quantum.custom "CNOT"() %out_qubits_27#0, %30 : !quantum.bit, !quantum.bit
      %31 = quantum.extract %0[ 30] : !quantum.reg -> !quantum.bit
      %out_qubits_29:2 = quantum.custom "CNOT"() %out_qubits_28#0, %31 : !quantum.bit, !quantum.bit
      %32 = quantum.extract %0[ 31] : !quantum.reg -> !quantum.bit
      %out_qubits_30:2 = quantum.custom "CNOT"() %out_qubits_29#0, %32 : !quantum.bit, !quantum.bit
      %33 = quantum.extract %0[ 32] : !quantum.reg -> !quantum.bit
      %out_qubits_31:2 = quantum.custom "CNOT"() %out_qubits_30#0, %33 : !quantum.bit, !quantum.bit
      %34 = quantum.extract %0[ 33] : !quantum.reg -> !quantum.bit
      %out_qubits_32:2 = quantum.custom "CNOT"() %out_qubits_31#0, %34 : !quantum.bit, !quantum.bit
      %35 = quantum.extract %0[ 34] : !quantum.reg -> !quantum.bit
      %out_qubits_33:2 = quantum.custom "CNOT"() %out_qubits_32#0, %35 : !quantum.bit, !quantum.bit
      %36 = quantum.extract %0[ 35] : !quantum.reg -> !quantum.bit
      %out_qubits_34:2 = quantum.custom "CNOT"() %out_qubits_33#0, %36 : !quantum.bit, !quantum.bit
      %37 = quantum.extract %0[ 36] : !quantum.reg -> !quantum.bit
      %out_qubits_35:2 = quantum.custom "CNOT"() %out_qubits_34#0, %37 : !quantum.bit, !quantum.bit
      %38 = quantum.extract %0[ 37] : !quantum.reg -> !quantum.bit
      %out_qubits_36:2 = quantum.custom "CNOT"() %out_qubits_35#0, %38 : !quantum.bit, !quantum.bit
      %39 = quantum.extract %0[ 38] : !quantum.reg -> !quantum.bit
      %out_qubits_37:2 = quantum.custom "CNOT"() %out_qubits_36#0, %39 : !quantum.bit, !quantum.bit
      %40 = quantum.extract %0[ 39] : !quantum.reg -> !quantum.bit
      %out_qubits_38:2 = quantum.custom "CNOT"() %out_qubits_37#0, %40 : !quantum.bit, !quantum.bit
      %41 = quantum.extract %0[ 40] : !quantum.reg -> !quantum.bit
      %out_qubits_39:2 = quantum.custom "CNOT"() %out_qubits_38#0, %41 : !quantum.bit, !quantum.bit
      %42 = quantum.extract %0[ 41] : !quantum.reg -> !quantum.bit
      %out_qubits_40:2 = quantum.custom "CNOT"() %out_qubits_39#0, %42 : !quantum.bit, !quantum.bit
      %43 = quantum.extract %0[ 42] : !quantum.reg -> !quantum.bit
      %out_qubits_41:2 = quantum.custom "CNOT"() %out_qubits_40#0, %43 : !quantum.bit, !quantum.bit
      %44 = quantum.extract %0[ 43] : !quantum.reg -> !quantum.bit
      %out_qubits_42:2 = quantum.custom "CNOT"() %out_qubits_41#0, %44 : !quantum.bit, !quantum.bit
      %45 = quantum.extract %0[ 44] : !quantum.reg -> !quantum.bit
      %out_qubits_43:2 = quantum.custom "CNOT"() %out_qubits_42#0, %45 : !quantum.bit, !quantum.bit
      %46 = quantum.extract %0[ 45] : !quantum.reg -> !quantum.bit
      %out_qubits_44:2 = quantum.custom "CNOT"() %out_qubits_43#0, %46 : !quantum.bit, !quantum.bit
      %47 = quantum.extract %0[ 46] : !quantum.reg -> !quantum.bit
      %out_qubits_45:2 = quantum.custom "CNOT"() %out_qubits_44#0, %47 : !quantum.bit, !quantum.bit
      %48 = quantum.extract %0[ 47] : !quantum.reg -> !quantum.bit
      %out_qubits_46:2 = quantum.custom "CNOT"() %out_qubits_45#0, %48 : !quantum.bit, !quantum.bit
      %49 = quantum.extract %0[ 48] : !quantum.reg -> !quantum.bit
      %out_qubits_47:2 = quantum.custom "CNOT"() %out_qubits_46#0, %49 : !quantum.bit, !quantum.bit
      %50 = quantum.extract %0[ 49] : !quantum.reg -> !quantum.bit
      %out_qubits_48:2 = quantum.custom "CNOT"() %out_qubits_47#0, %50 : !quantum.bit, !quantum.bit
      %51 = quantum.extract %0[ 50] : !quantum.reg -> !quantum.bit
      %out_qubits_49:2 = quantum.custom "CNOT"() %out_qubits_48#0, %51 : !quantum.bit, !quantum.bit
      %52 = quantum.extract %0[ 51] : !quantum.reg -> !quantum.bit
      %out_qubits_50:2 = quantum.custom "CNOT"() %out_qubits_49#0, %52 : !quantum.bit, !quantum.bit
      %53 = quantum.extract %0[ 52] : !quantum.reg -> !quantum.bit
      %out_qubits_51:2 = quantum.custom "CNOT"() %out_qubits_50#0, %53 : !quantum.bit, !quantum.bit
      %54 = quantum.extract %0[ 53] : !quantum.reg -> !quantum.bit
      %out_qubits_52:2 = quantum.custom "CNOT"() %out_qubits_51#0, %54 : !quantum.bit, !quantum.bit
      %55 = quantum.extract %0[ 54] : !quantum.reg -> !quantum.bit
      %out_qubits_53:2 = quantum.custom "CNOT"() %out_qubits_52#0, %55 : !quantum.bit, !quantum.bit
      %56 = quantum.extract %0[ 55] : !quantum.reg -> !quantum.bit
      %out_qubits_54:2 = quantum.custom "CNOT"() %out_qubits_53#0, %56 : !quantum.bit, !quantum.bit
      %57 = quantum.extract %0[ 56] : !quantum.reg -> !quantum.bit
      %out_qubits_55:2 = quantum.custom "CNOT"() %out_qubits_54#0, %57 : !quantum.bit, !quantum.bit
      %58 = quantum.extract %0[ 57] : !quantum.reg -> !quantum.bit
      %out_qubits_56:2 = quantum.custom "CNOT"() %out_qubits_55#0, %58 : !quantum.bit, !quantum.bit
      %59 = quantum.extract %0[ 58] : !quantum.reg -> !quantum.bit
      %out_qubits_57:2 = quantum.custom "CNOT"() %out_qubits_56#0, %59 : !quantum.bit, !quantum.bit
      %60 = quantum.extract %0[ 59] : !quantum.reg -> !quantum.bit
      %out_qubits_58:2 = quantum.custom "CNOT"() %out_qubits_57#0, %60 : !quantum.bit, !quantum.bit
      %61 = quantum.extract %0[ 60] : !quantum.reg -> !quantum.bit
      %out_qubits_59:2 = quantum.custom "CNOT"() %out_qubits_58#0, %61 : !quantum.bit, !quantum.bit
      %62 = quantum.extract %0[ 61] : !quantum.reg -> !quantum.bit
      %out_qubits_60:2 = quantum.custom "CNOT"() %out_qubits_59#0, %62 : !quantum.bit, !quantum.bit
      %63 = quantum.extract %0[ 62] : !quantum.reg -> !quantum.bit
      %out_qubits_61:2 = quantum.custom "CNOT"() %out_qubits_60#0, %63 : !quantum.bit, !quantum.bit
      %64 = quantum.extract %0[ 63] : !quantum.reg -> !quantum.bit
      %out_qubits_62:2 = quantum.custom "CNOT"() %out_qubits_61#0, %64 : !quantum.bit, !quantum.bit
      %65 = quantum.extract %0[ 64] : !quantum.reg -> !quantum.bit
      %out_qubits_63:2 = quantum.custom "CNOT"() %out_qubits_62#0, %65 : !quantum.bit, !quantum.bit
      %mres, %out_qubit = quantum.measure %out_qubits_63#0 : i1, !quantum.bit
      %from_elements = tensor.from_elements %mres : tensor<i1>
      %mres_64, %out_qubit_65 = quantum.measure %out_qubits_0#1 : i1, !quantum.bit
      %from_elements_66 = tensor.from_elements %mres_64 : tensor<i1>
      %mres_67, %out_qubit_68 = quantum.measure %out_qubits_1#1 : i1, !quantum.bit
      %from_elements_69 = tensor.from_elements %mres_67 : tensor<i1>
      %mres_70, %out_qubit_71 = quantum.measure %out_qubits_2#1 : i1, !quantum.bit
      %from_elements_72 = tensor.from_elements %mres_70 : tensor<i1>
      %mres_73, %out_qubit_74 = quantum.measure %out_qubits_3#1 : i1, !quantum.bit
      %from_elements_75 = tensor.from_elements %mres_73 : tensor<i1>
      %mres_76, %out_qubit_77 = quantum.measure %out_qubits_4#1 : i1, !quantum.bit
      %from_elements_78 = tensor.from_elements %mres_76 : tensor<i1>
      %mres_79, %out_qubit_80 = quantum.measure %out_qubits_5#1 : i1, !quantum.bit
      %from_elements_81 = tensor.from_elements %mres_79 : tensor<i1>
      %mres_82, %out_qubit_83 = quantum.measure %out_qubits_6#1 : i1, !quantum.bit
      %from_elements_84 = tensor.from_elements %mres_82 : tensor<i1>
      %mres_85, %out_qubit_86 = quantum.measure %out_qubits_7#1 : i1, !quantum.bit
      %from_elements_87 = tensor.from_elements %mres_85 : tensor<i1>
      %mres_88, %out_qubit_89 = quantum.measure %out_qubits_8#1 : i1, !quantum.bit
      %from_elements_90 = tensor.from_elements %mres_88 : tensor<i1>
      %mres_91, %out_qubit_92 = quantum.measure %out_qubits_9#1 : i1, !quantum.bit
      %from_elements_93 = tensor.from_elements %mres_91 : tensor<i1>
      %mres_94, %out_qubit_95 = quantum.measure %out_qubits_10#1 : i1, !quantum.bit
      %from_elements_96 = tensor.from_elements %mres_94 : tensor<i1>
      %mres_97, %out_qubit_98 = quantum.measure %out_qubits_11#1 : i1, !quantum.bit
      %from_elements_99 = tensor.from_elements %mres_97 : tensor<i1>
      %mres_100, %out_qubit_101 = quantum.measure %out_qubits_12#1 : i1, !quantum.bit
      %from_elements_102 = tensor.from_elements %mres_100 : tensor<i1>
      %mres_103, %out_qubit_104 = quantum.measure %out_qubits_13#1 : i1, !quantum.bit
      %from_elements_105 = tensor.from_elements %mres_103 : tensor<i1>
      %mres_106, %out_qubit_107 = quantum.measure %out_qubits_14#1 : i1, !quantum.bit
      %from_elements_108 = tensor.from_elements %mres_106 : tensor<i1>
      %mres_109, %out_qubit_110 = quantum.measure %out_qubits_15#1 : i1, !quantum.bit
      %from_elements_111 = tensor.from_elements %mres_109 : tensor<i1>
      %mres_112, %out_qubit_113 = quantum.measure %out_qubits_16#1 : i1, !quantum.bit
      %from_elements_114 = tensor.from_elements %mres_112 : tensor<i1>
      %mres_115, %out_qubit_116 = quantum.measure %out_qubits_17#1 : i1, !quantum.bit
      %from_elements_117 = tensor.from_elements %mres_115 : tensor<i1>
      %mres_118, %out_qubit_119 = quantum.measure %out_qubits_18#1 : i1, !quantum.bit
      %from_elements_120 = tensor.from_elements %mres_118 : tensor<i1>
      %mres_121, %out_qubit_122 = quantum.measure %out_qubits_19#1 : i1, !quantum.bit
      %from_elements_123 = tensor.from_elements %mres_121 : tensor<i1>
      %mres_124, %out_qubit_125 = quantum.measure %out_qubits_20#1 : i1, !quantum.bit
      %from_elements_126 = tensor.from_elements %mres_124 : tensor<i1>
      %mres_127, %out_qubit_128 = quantum.measure %out_qubits_21#1 : i1, !quantum.bit
      %from_elements_129 = tensor.from_elements %mres_127 : tensor<i1>
      %mres_130, %out_qubit_131 = quantum.measure %out_qubits_22#1 : i1, !quantum.bit
      %from_elements_132 = tensor.from_elements %mres_130 : tensor<i1>
      %mres_133, %out_qubit_134 = quantum.measure %out_qubits_23#1 : i1, !quantum.bit
      %from_elements_135 = tensor.from_elements %mres_133 : tensor<i1>
      %mres_136, %out_qubit_137 = quantum.measure %out_qubits_24#1 : i1, !quantum.bit
      %from_elements_138 = tensor.from_elements %mres_136 : tensor<i1>
      %mres_139, %out_qubit_140 = quantum.measure %out_qubits_25#1 : i1, !quantum.bit
      %from_elements_141 = tensor.from_elements %mres_139 : tensor<i1>
      %mres_142, %out_qubit_143 = quantum.measure %out_qubits_26#1 : i1, !quantum.bit
      %from_elements_144 = tensor.from_elements %mres_142 : tensor<i1>
      %mres_145, %out_qubit_146 = quantum.measure %out_qubits_27#1 : i1, !quantum.bit
      %from_elements_147 = tensor.from_elements %mres_145 : tensor<i1>
      %mres_148, %out_qubit_149 = quantum.measure %out_qubits_28#1 : i1, !quantum.bit
      %from_elements_150 = tensor.from_elements %mres_148 : tensor<i1>
      %mres_151, %out_qubit_152 = quantum.measure %out_qubits_29#1 : i1, !quantum.bit
      %from_elements_153 = tensor.from_elements %mres_151 : tensor<i1>
      %mres_154, %out_qubit_155 = quantum.measure %out_qubits_30#1 : i1, !quantum.bit
      %from_elements_156 = tensor.from_elements %mres_154 : tensor<i1>
      %mres_157, %out_qubit_158 = quantum.measure %out_qubits_31#1 : i1, !quantum.bit
      %from_elements_159 = tensor.from_elements %mres_157 : tensor<i1>
      %mres_160, %out_qubit_161 = quantum.measure %out_qubits_32#1 : i1, !quantum.bit
      %from_elements_162 = tensor.from_elements %mres_160 : tensor<i1>
      %mres_163, %out_qubit_164 = quantum.measure %out_qubits_33#1 : i1, !quantum.bit
      %from_elements_165 = tensor.from_elements %mres_163 : tensor<i1>
      %mres_166, %out_qubit_167 = quantum.measure %out_qubits_34#1 : i1, !quantum.bit
      %from_elements_168 = tensor.from_elements %mres_166 : tensor<i1>
      %mres_169, %out_qubit_170 = quantum.measure %out_qubits_35#1 : i1, !quantum.bit
      %from_elements_171 = tensor.from_elements %mres_169 : tensor<i1>
      %mres_172, %out_qubit_173 = quantum.measure %out_qubits_36#1 : i1, !quantum.bit
      %from_elements_174 = tensor.from_elements %mres_172 : tensor<i1>
      %mres_175, %out_qubit_176 = quantum.measure %out_qubits_37#1 : i1, !quantum.bit
      %from_elements_177 = tensor.from_elements %mres_175 : tensor<i1>
      %mres_178, %out_qubit_179 = quantum.measure %out_qubits_38#1 : i1, !quantum.bit
      %from_elements_180 = tensor.from_elements %mres_178 : tensor<i1>
      %mres_181, %out_qubit_182 = quantum.measure %out_qubits_39#1 : i1, !quantum.bit
      %from_elements_183 = tensor.from_elements %mres_181 : tensor<i1>
      %mres_184, %out_qubit_185 = quantum.measure %out_qubits_40#1 : i1, !quantum.bit
      %from_elements_186 = tensor.from_elements %mres_184 : tensor<i1>
      %mres_187, %out_qubit_188 = quantum.measure %out_qubits_41#1 : i1, !quantum.bit
      %from_elements_189 = tensor.from_elements %mres_187 : tensor<i1>
      %mres_190, %out_qubit_191 = quantum.measure %out_qubits_42#1 : i1, !quantum.bit
      %from_elements_192 = tensor.from_elements %mres_190 : tensor<i1>
      %mres_193, %out_qubit_194 = quantum.measure %out_qubits_43#1 : i1, !quantum.bit
      %from_elements_195 = tensor.from_elements %mres_193 : tensor<i1>
      %mres_196, %out_qubit_197 = quantum.measure %out_qubits_44#1 : i1, !quantum.bit
      %from_elements_198 = tensor.from_elements %mres_196 : tensor<i1>
      %mres_199, %out_qubit_200 = quantum.measure %out_qubits_45#1 : i1, !quantum.bit
      %from_elements_201 = tensor.from_elements %mres_199 : tensor<i1>
      %mres_202, %out_qubit_203 = quantum.measure %out_qubits_46#1 : i1, !quantum.bit
      %from_elements_204 = tensor.from_elements %mres_202 : tensor<i1>
      %mres_205, %out_qubit_206 = quantum.measure %out_qubits_47#1 : i1, !quantum.bit
      %from_elements_207 = tensor.from_elements %mres_205 : tensor<i1>
      %mres_208, %out_qubit_209 = quantum.measure %out_qubits_48#1 : i1, !quantum.bit
      %from_elements_210 = tensor.from_elements %mres_208 : tensor<i1>
      %mres_211, %out_qubit_212 = quantum.measure %out_qubits_49#1 : i1, !quantum.bit
      %from_elements_213 = tensor.from_elements %mres_211 : tensor<i1>
      %mres_214, %out_qubit_215 = quantum.measure %out_qubits_50#1 : i1, !quantum.bit
      %from_elements_216 = tensor.from_elements %mres_214 : tensor<i1>
      %mres_217, %out_qubit_218 = quantum.measure %out_qubits_51#1 : i1, !quantum.bit
      %from_elements_219 = tensor.from_elements %mres_217 : tensor<i1>
      %mres_220, %out_qubit_221 = quantum.measure %out_qubits_52#1 : i1, !quantum.bit
      %from_elements_222 = tensor.from_elements %mres_220 : tensor<i1>
      %mres_223, %out_qubit_224 = quantum.measure %out_qubits_53#1 : i1, !quantum.bit
      %from_elements_225 = tensor.from_elements %mres_223 : tensor<i1>
      %mres_226, %out_qubit_227 = quantum.measure %out_qubits_54#1 : i1, !quantum.bit
      %from_elements_228 = tensor.from_elements %mres_226 : tensor<i1>
      %mres_229, %out_qubit_230 = quantum.measure %out_qubits_55#1 : i1, !quantum.bit
      %from_elements_231 = tensor.from_elements %mres_229 : tensor<i1>
      %mres_232, %out_qubit_233 = quantum.measure %out_qubits_56#1 : i1, !quantum.bit
      %from_elements_234 = tensor.from_elements %mres_232 : tensor<i1>
      %mres_235, %out_qubit_236 = quantum.measure %out_qubits_57#1 : i1, !quantum.bit
      %from_elements_237 = tensor.from_elements %mres_235 : tensor<i1>
      %mres_238, %out_qubit_239 = quantum.measure %out_qubits_58#1 : i1, !quantum.bit
      %from_elements_240 = tensor.from_elements %mres_238 : tensor<i1>
      %mres_241, %out_qubit_242 = quantum.measure %out_qubits_59#1 : i1, !quantum.bit
      %from_elements_243 = tensor.from_elements %mres_241 : tensor<i1>
      %mres_244, %out_qubit_245 = quantum.measure %out_qubits_60#1 : i1, !quantum.bit
      %from_elements_246 = tensor.from_elements %mres_244 : tensor<i1>
      %mres_247, %out_qubit_248 = quantum.measure %out_qubits_61#1 : i1, !quantum.bit
      %from_elements_249 = tensor.from_elements %mres_247 : tensor<i1>
      %mres_250, %out_qubit_251 = quantum.measure %out_qubits_62#1 : i1, !quantum.bit
      %from_elements_252 = tensor.from_elements %mres_250 : tensor<i1>
      %mres_253, %out_qubit_254 = quantum.measure %out_qubits_63#1 : i1, !quantum.bit
      %from_elements_255 = tensor.from_elements %mres_253 : tensor<i1>
      %66 = quantum.insert %0[ 0], %out_qubit : !quantum.reg, !quantum.bit
      %67 = quantum.insert %66[ 1], %out_qubit_65 : !quantum.reg, !quantum.bit
      %68 = quantum.insert %67[ 2], %out_qubit_68 : !quantum.reg, !quantum.bit
      %69 = quantum.insert %68[ 3], %out_qubit_71 : !quantum.reg, !quantum.bit
      %70 = quantum.insert %69[ 4], %out_qubit_74 : !quantum.reg, !quantum.bit
      %71 = quantum.insert %70[ 5], %out_qubit_77 : !quantum.reg, !quantum.bit
      %72 = quantum.insert %71[ 6], %out_qubit_80 : !quantum.reg, !quantum.bit
      %73 = quantum.insert %72[ 7], %out_qubit_83 : !quantum.reg, !quantum.bit
      %74 = quantum.insert %73[ 8], %out_qubit_86 : !quantum.reg, !quantum.bit
      %75 = quantum.insert %74[ 9], %out_qubit_89 : !quantum.reg, !quantum.bit
      %76 = quantum.insert %75[ 10], %out_qubit_92 : !quantum.reg, !quantum.bit
      %77 = quantum.insert %76[ 11], %out_qubit_95 : !quantum.reg, !quantum.bit
      %78 = quantum.insert %77[ 12], %out_qubit_98 : !quantum.reg, !quantum.bit
      %79 = quantum.insert %78[ 13], %out_qubit_101 : !quantum.reg, !quantum.bit
      %80 = quantum.insert %79[ 14], %out_qubit_104 : !quantum.reg, !quantum.bit
      %81 = quantum.insert %80[ 15], %out_qubit_107 : !quantum.reg, !quantum.bit
      %82 = quantum.insert %81[ 16], %out_qubit_110 : !quantum.reg, !quantum.bit
      %83 = quantum.insert %82[ 17], %out_qubit_113 : !quantum.reg, !quantum.bit
      %84 = quantum.insert %83[ 18], %out_qubit_116 : !quantum.reg, !quantum.bit
      %85 = quantum.insert %84[ 19], %out_qubit_119 : !quantum.reg, !quantum.bit
      %86 = quantum.insert %85[ 20], %out_qubit_122 : !quantum.reg, !quantum.bit
      %87 = quantum.insert %86[ 21], %out_qubit_125 : !quantum.reg, !quantum.bit
      %88 = quantum.insert %87[ 22], %out_qubit_128 : !quantum.reg, !quantum.bit
      %89 = quantum.insert %88[ 23], %out_qubit_131 : !quantum.reg, !quantum.bit
      %90 = quantum.insert %89[ 24], %out_qubit_134 : !quantum.reg, !quantum.bit
      %91 = quantum.insert %90[ 25], %out_qubit_137 : !quantum.reg, !quantum.bit
      %92 = quantum.insert %91[ 26], %out_qubit_140 : !quantum.reg, !quantum.bit
      %93 = quantum.insert %92[ 27], %out_qubit_143 : !quantum.reg, !quantum.bit
      %94 = quantum.insert %93[ 28], %out_qubit_146 : !quantum.reg, !quantum.bit
      %95 = quantum.insert %94[ 29], %out_qubit_149 : !quantum.reg, !quantum.bit
      %96 = quantum.insert %95[ 30], %out_qubit_152 : !quantum.reg, !quantum.bit
      %97 = quantum.insert %96[ 31], %out_qubit_155 : !quantum.reg, !quantum.bit
      %98 = quantum.insert %97[ 32], %out_qubit_158 : !quantum.reg, !quantum.bit
      %99 = quantum.insert %98[ 33], %out_qubit_161 : !quantum.reg, !quantum.bit
      %100 = quantum.insert %99[ 34], %out_qubit_164 : !quantum.reg, !quantum.bit
      %101 = quantum.insert %100[ 35], %out_qubit_167 : !quantum.reg, !quantum.bit
      %102 = quantum.insert %101[ 36], %out_qubit_170 : !quantum.reg, !quantum.bit
      %103 = quantum.insert %102[ 37], %out_qubit_173 : !quantum.reg, !quantum.bit
      %104 = quantum.insert %103[ 38], %out_qubit_176 : !quantum.reg, !quantum.bit
      %105 = quantum.insert %104[ 39], %out_qubit_179 : !quantum.reg, !quantum.bit
      %106 = quantum.insert %105[ 40], %out_qubit_182 : !quantum.reg, !quantum.bit
      %107 = quantum.insert %106[ 41], %out_qubit_185 : !quantum.reg, !quantum.bit
      %108 = quantum.insert %107[ 42], %out_qubit_188 : !quantum.reg, !quantum.bit
      %109 = quantum.insert %108[ 43], %out_qubit_191 : !quantum.reg, !quantum.bit
      %110 = quantum.insert %109[ 44], %out_qubit_194 : !quantum.reg, !quantum.bit
      %111 = quantum.insert %110[ 45], %out_qubit_197 : !quantum.reg, !quantum.bit
      %112 = quantum.insert %111[ 46], %out_qubit_200 : !quantum.reg, !quantum.bit
      %113 = quantum.insert %112[ 47], %out_qubit_203 : !quantum.reg, !quantum.bit
      %114 = quantum.insert %113[ 48], %out_qubit_206 : !quantum.reg, !quantum.bit
      %115 = quantum.insert %114[ 49], %out_qubit_209 : !quantum.reg, !quantum.bit
      %116 = quantum.insert %115[ 50], %out_qubit_212 : !quantum.reg, !quantum.bit
      %117 = quantum.insert %116[ 51], %out_qubit_215 : !quantum.reg, !quantum.bit
      %118 = quantum.insert %117[ 52], %out_qubit_218 : !quantum.reg, !quantum.bit
      %119 = quantum.insert %118[ 53], %out_qubit_221 : !quantum.reg, !quantum.bit
      %120 = quantum.insert %119[ 54], %out_qubit_224 : !quantum.reg, !quantum.bit
      %121 = quantum.insert %120[ 55], %out_qubit_227 : !quantum.reg, !quantum.bit
      %122 = quantum.insert %121[ 56], %out_qubit_230 : !quantum.reg, !quantum.bit
      %123 = quantum.insert %122[ 57], %out_qubit_233 : !quantum.reg, !quantum.bit
      %124 = quantum.insert %123[ 58], %out_qubit_236 : !quantum.reg, !quantum.bit
      %125 = quantum.insert %124[ 59], %out_qubit_239 : !quantum.reg, !quantum.bit
      %126 = quantum.insert %125[ 60], %out_qubit_242 : !quantum.reg, !quantum.bit
      %127 = quantum.insert %126[ 61], %out_qubit_245 : !quantum.reg, !quantum.bit
      %128 = quantum.insert %127[ 62], %out_qubit_248 : !quantum.reg, !quantum.bit
      %129 = quantum.insert %128[ 63], %out_qubit_251 : !quantum.reg, !quantum.bit
      %130 = quantum.insert %129[ 64], %out_qubit_254 : !quantum.reg, !quantum.bit
      quantum.dealloc %130 : !quantum.reg
      quantum.device_release
      return %from_elements, %from_elements_66, %from_elements_69, %from_elements_72, %from_elements_75, %from_elements_78, %from_elements_81, %from_elements_84, %from_elements_87, %from_elements_90, %from_elements_93, %from_elements_96, %from_elements_99, %from_elements_102, %from_elements_105, %from_elements_108, %from_elements_111, %from_elements_114, %from_elements_117, %from_elements_120, %from_elements_123, %from_elements_126, %from_elements_129, %from_elements_132, %from_elements_135, %from_elements_138, %from_elements_141, %from_elements_144, %from_elements_147, %from_elements_150, %from_elements_153, %from_elements_156, %from_elements_159, %from_elements_162, %from_elements_165, %from_elements_168, %from_elements_171, %from_elements_174, %from_elements_177, %from_elements_180, %from_elements_183, %from_elements_186, %from_elements_189, %from_elements_192, %from_elements_195, %from_elements_198, %from_elements_201, %from_elements_204, %from_elements_207, %from_elements_210, %from_elements_213, %from_elements_216, %from_elements_219, %from_elements_222, %from_elements_225, %from_elements_228, %from_elements_231, %from_elements_234, %from_elements_237, %from_elements_240, %from_elements_243, %from_elements_246, %from_elements_249, %from_elements_252, %from_elements_255 : tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>
    }
  }
  func.func @setup() {
    quantum.init
    return
  }
  func.func @teardown() {
    quantum.finalize
    return
  }
}