module @run_ghz {
  func.func public @jit_run_ghz() -> (tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>) attributes {llvm.emit_c_interface} {
    %0:70 = catalyst.launch_kernel @module_ghz::@ghz() : () -> (tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>)
    return %0#0, %0#1, %0#2, %0#3, %0#4, %0#5, %0#6, %0#7, %0#8, %0#9, %0#10, %0#11, %0#12, %0#13, %0#14, %0#15, %0#16, %0#17, %0#18, %0#19, %0#20, %0#21, %0#22, %0#23, %0#24, %0#25, %0#26, %0#27, %0#28, %0#29, %0#30, %0#31, %0#32, %0#33, %0#34, %0#35, %0#36, %0#37, %0#38, %0#39, %0#40, %0#41, %0#42, %0#43, %0#44, %0#45, %0#46, %0#47, %0#48, %0#49, %0#50, %0#51, %0#52, %0#53, %0#54, %0#55, %0#56, %0#57, %0#58, %0#59, %0#60, %0#61, %0#62, %0#63, %0#64, %0#65, %0#66, %0#67, %0#68, %0#69 : tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>
  }
  module @module_ghz {
    module attributes {transform.with_named_sequence} {
      transform.named_sequence @__transform_main(%arg0: !transform.op<"builtin.module">) {
        transform.yield 
      }
    }
    func.func public @ghz() -> (tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>) attributes {diff_method = "parameter-shift", llvm.linkage = #llvm.linkage<internal>, qnode} {
      %c0_i64 = arith.constant 0 : i64
      quantum.device shots(%c0_i64) ["/home/kew/.venv/lib/python3.10/site-packages/pennylane_lightning/liblightning_qubit_catalyst.so", "LightningSimulator", "{'mcmc': False, 'num_burnin': 0, 'kernel_name': None}"]
      %0 = quantum.alloc( 70) : !quantum.reg
      %1 = quantum.extract %0[ 0] : !quantum.reg -> !quantum.bit
      %out_qubits = quantum.custom "Hadamard"() %1 : !quantum.bit
      %2 = quantum.extract %0[ 1] : !quantum.reg -> !quantum.bit
      %out_qubits_0:2 = quantum.custom "CNOT"() %out_qubits, %2 : !quantum.bit, !quantum.bit
      %3 = quantum.extract %0[ 2] : !quantum.reg -> !quantum.bit
      %out_qubits_1:2 = quantum.custom "CNOT"() %out_qubits_0#0, %3 : !quantum.bit, !quantum.bit
      %4 = quantum.extract %0[ 3] : !quantum.reg -> !quantum.bit
      %out_qubits_2:2 = quantum.custom "CNOT"() %out_qubits_1#0, %4 : !quantum.bit, !quantum.bit
      %5 = quantum.extract %0[ 4] : !quantum.reg -> !quantum.bit
      %out_qubits_3:2 = quantum.custom "CNOT"() %out_qubits_2#0, %5 : !quantum.bit, !quantum.bit
      %6 = quantum.extract %0[ 5] : !quantum.reg -> !quantum.bit
      %out_qubits_4:2 = quantum.custom "CNOT"() %out_qubits_3#0, %6 : !quantum.bit, !quantum.bit
      %7 = quantum.extract %0[ 6] : !quantum.reg -> !quantum.bit
      %out_qubits_5:2 = quantum.custom "CNOT"() %out_qubits_4#0, %7 : !quantum.bit, !quantum.bit
      %8 = quantum.extract %0[ 7] : !quantum.reg -> !quantum.bit
      %out_qubits_6:2 = quantum.custom "CNOT"() %out_qubits_5#0, %8 : !quantum.bit, !quantum.bit
      %9 = quantum.extract %0[ 8] : !quantum.reg -> !quantum.bit
      %out_qubits_7:2 = quantum.custom "CNOT"() %out_qubits_6#0, %9 : !quantum.bit, !quantum.bit
      %10 = quantum.extract %0[ 9] : !quantum.reg -> !quantum.bit
      %out_qubits_8:2 = quantum.custom "CNOT"() %out_qubits_7#0, %10 : !quantum.bit, !quantum.bit
      %11 = quantum.extract %0[ 10] : !quantum.reg -> !quantum.bit
      %out_qubits_9:2 = quantum.custom "CNOT"() %out_qubits_8#0, %11 : !quantum.bit, !quantum.bit
      %12 = quantum.extract %0[ 11] : !quantum.reg -> !quantum.bit
      %out_qubits_10:2 = quantum.custom "CNOT"() %out_qubits_9#0, %12 : !quantum.bit, !quantum.bit
      %13 = quantum.extract %0[ 12] : !quantum.reg -> !quantum.bit
      %out_qubits_11:2 = quantum.custom "CNOT"() %out_qubits_10#0, %13 : !quantum.bit, !quantum.bit
      %14 = quantum.extract %0[ 13] : !quantum.reg -> !quantum.bit
      %out_qubits_12:2 = quantum.custom "CNOT"() %out_qubits_11#0, %14 : !quantum.bit, !quantum.bit
      %15 = quantum.extract %0[ 14] : !quantum.reg -> !quantum.bit
      %out_qubits_13:2 = quantum.custom "CNOT"() %out_qubits_12#0, %15 : !quantum.bit, !quantum.bit
      %16 = quantum.extract %0[ 15] : !quantum.reg -> !quantum.bit
      %out_qubits_14:2 = quantum.custom "CNOT"() %out_qubits_13#0, %16 : !quantum.bit, !quantum.bit
      %17 = quantum.extract %0[ 16] : !quantum.reg -> !quantum.bit
      %out_qubits_15:2 = quantum.custom "CNOT"() %out_qubits_14#0, %17 : !quantum.bit, !quantum.bit
      %18 = quantum.extract %0[ 17] : !quantum.reg -> !quantum.bit
      %out_qubits_16:2 = quantum.custom "CNOT"() %out_qubits_15#0, %18 : !quantum.bit, !quantum.bit
      %19 = quantum.extract %0[ 18] : !quantum.reg -> !quantum.bit
      %out_qubits_17:2 = quantum.custom "CNOT"() %out_qubits_16#0, %19 : !quantum.bit, !quantum.bit
      %20 = quantum.extract %0[ 19] : !quantum.reg -> !quantum.bit
      %out_qubits_18:2 = quantum.custom "CNOT"() %out_qubits_17#0, %20 : !quantum.bit, !quantum.bit
      %21 = quantum.extract %0[ 20] : !quantum.reg -> !quantum.bit
      %out_qubits_19:2 = quantum.custom "CNOT"() %out_qubits_18#0, %21 : !quantum.bit, !quantum.bit
      %22 = quantum.extract %0[ 21] : !quantum.reg -> !quantum.bit
      %out_qubits_20:2 = quantum.custom "CNOT"() %out_qubits_19#0, %22 : !quantum.bit, !quantum.bit
      %23 = quantum.extract %0[ 22] : !quantum.reg -> !quantum.bit
      %out_qubits_21:2 = quantum.custom "CNOT"() %out_qubits_20#0, %23 : !quantum.bit, !quantum.bit
      %24 = quantum.extract %0[ 23] : !quantum.reg -> !quantum.bit
      %out_qubits_22:2 = quantum.custom "CNOT"() %out_qubits_21#0, %24 : !quantum.bit, !quantum.bit
      %25 = quantum.extract %0[ 24] : !quantum.reg -> !quantum.bit
      %out_qubits_23:2 = quantum.custom "CNOT"() %out_qubits_22#0, %25 : !quantum.bit, !quantum.bit
      %26 = quantum.extract %0[ 25] : !quantum.reg -> !quantum.bit
      %out_qubits_24:2 = quantum.custom "CNOT"() %out_qubits_23#0, %26 : !quantum.bit, !quantum.bit
      %27 = quantum.extract %0[ 26] : !quantum.reg -> !quantum.bit
      %out_qubits_25:2 = quantum.custom "CNOT"() %out_qubits_24#0, %27 : !quantum.bit, !quantum.bit
      %28 = quantum.extract %0[ 27] : !quantum.reg -> !quantum.bit
      %out_qubits_26:2 = quantum.custom "CNOT"() %out_qubits_25#0, %28 : !quantum.bit, !quantum.bit
      %29 = quantum.extract %0[ 28] : !quantum.reg -> !quantum.bit
      %out_qubits_27:2 = quantum.custom "CNOT"() %out_qubits_26#0, %29 : !quantum.bit, !quantum.bit
      %30 = quantum.extract %0[ 29] : !quantum.reg -> !quantum.bit
      %out_qubits_28:2 = quantum.custom "CNOT"() %out_qubits_27#0, %30 : !quantum.bit, !quantum.bit
      %31 = quantum.extract %0[ 30] : !quantum.reg -> !quantum.bit
      %out_qubits_29:2 = quantum.custom "CNOT"() %out_qubits_28#0, %31 : !quantum.bit, !quantum.bit
      %32 = quantum.extract %0[ 31] : !quantum.reg -> !quantum.bit
      %out_qubits_30:2 = quantum.custom "CNOT"() %out_qubits_29#0, %32 : !quantum.bit, !quantum.bit
      %33 = quantum.extract %0[ 32] : !quantum.reg -> !quantum.bit
      %out_qubits_31:2 = quantum.custom "CNOT"() %out_qubits_30#0, %33 : !quantum.bit, !quantum.bit
      %34 = quantum.extract %0[ 33] : !quantum.reg -> !quantum.bit
      %out_qubits_32:2 = quantum.custom "CNOT"() %out_qubits_31#0, %34 : !quantum.bit, !quantum.bit
      %35 = quantum.extract %0[ 34] : !quantum.reg -> !quantum.bit
      %out_qubits_33:2 = quantum.custom "CNOT"() %out_qubits_32#0, %35 : !quantum.bit, !quantum.bit
      %36 = quantum.extract %0[ 35] : !quantum.reg -> !quantum.bit
      %out_qubits_34:2 = quantum.custom "CNOT"() %out_qubits_33#0, %36 : !quantum.bit, !quantum.bit
      %37 = quantum.extract %0[ 36] : !quantum.reg -> !quantum.bit
      %out_qubits_35:2 = quantum.custom "CNOT"() %out_qubits_34#0, %37 : !quantum.bit, !quantum.bit
      %38 = quantum.extract %0[ 37] : !quantum.reg -> !quantum.bit
      %out_qubits_36:2 = quantum.custom "CNOT"() %out_qubits_35#0, %38 : !quantum.bit, !quantum.bit
      %39 = quantum.extract %0[ 38] : !quantum.reg -> !quantum.bit
      %out_qubits_37:2 = quantum.custom "CNOT"() %out_qubits_36#0, %39 : !quantum.bit, !quantum.bit
      %40 = quantum.extract %0[ 39] : !quantum.reg -> !quantum.bit
      %out_qubits_38:2 = quantum.custom "CNOT"() %out_qubits_37#0, %40 : !quantum.bit, !quantum.bit
      %41 = quantum.extract %0[ 40] : !quantum.reg -> !quantum.bit
      %out_qubits_39:2 = quantum.custom "CNOT"() %out_qubits_38#0, %41 : !quantum.bit, !quantum.bit
      %42 = quantum.extract %0[ 41] : !quantum.reg -> !quantum.bit
      %out_qubits_40:2 = quantum.custom "CNOT"() %out_qubits_39#0, %42 : !quantum.bit, !quantum.bit
      %43 = quantum.extract %0[ 42] : !quantum.reg -> !quantum.bit
      %out_qubits_41:2 = quantum.custom "CNOT"() %out_qubits_40#0, %43 : !quantum.bit, !quantum.bit
      %44 = quantum.extract %0[ 43] : !quantum.reg -> !quantum.bit
      %out_qubits_42:2 = quantum.custom "CNOT"() %out_qubits_41#0, %44 : !quantum.bit, !quantum.bit
      %45 = quantum.extract %0[ 44] : !quantum.reg -> !quantum.bit
      %out_qubits_43:2 = quantum.custom "CNOT"() %out_qubits_42#0, %45 : !quantum.bit, !quantum.bit
      %46 = quantum.extract %0[ 45] : !quantum.reg -> !quantum.bit
      %out_qubits_44:2 = quantum.custom "CNOT"() %out_qubits_43#0, %46 : !quantum.bit, !quantum.bit
      %47 = quantum.extract %0[ 46] : !quantum.reg -> !quantum.bit
      %out_qubits_45:2 = quantum.custom "CNOT"() %out_qubits_44#0, %47 : !quantum.bit, !quantum.bit
      %48 = quantum.extract %0[ 47] : !quantum.reg -> !quantum.bit
      %out_qubits_46:2 = quantum.custom "CNOT"() %out_qubits_45#0, %48 : !quantum.bit, !quantum.bit
      %49 = quantum.extract %0[ 48] : !quantum.reg -> !quantum.bit
      %out_qubits_47:2 = quantum.custom "CNOT"() %out_qubits_46#0, %49 : !quantum.bit, !quantum.bit
      %50 = quantum.extract %0[ 49] : !quantum.reg -> !quantum.bit
      %out_qubits_48:2 = quantum.custom "CNOT"() %out_qubits_47#0, %50 : !quantum.bit, !quantum.bit
      %51 = quantum.extract %0[ 50] : !quantum.reg -> !quantum.bit
      %out_qubits_49:2 = quantum.custom "CNOT"() %out_qubits_48#0, %51 : !quantum.bit, !quantum.bit
      %52 = quantum.extract %0[ 51] : !quantum.reg -> !quantum.bit
      %out_qubits_50:2 = quantum.custom "CNOT"() %out_qubits_49#0, %52 : !quantum.bit, !quantum.bit
      %53 = quantum.extract %0[ 52] : !quantum.reg -> !quantum.bit
      %out_qubits_51:2 = quantum.custom "CNOT"() %out_qubits_50#0, %53 : !quantum.bit, !quantum.bit
      %54 = quantum.extract %0[ 53] : !quantum.reg -> !quantum.bit
      %out_qubits_52:2 = quantum.custom "CNOT"() %out_qubits_51#0, %54 : !quantum.bit, !quantum.bit
      %55 = quantum.extract %0[ 54] : !quantum.reg -> !quantum.bit
      %out_qubits_53:2 = quantum.custom "CNOT"() %out_qubits_52#0, %55 : !quantum.bit, !quantum.bit
      %56 = quantum.extract %0[ 55] : !quantum.reg -> !quantum.bit
      %out_qubits_54:2 = quantum.custom "CNOT"() %out_qubits_53#0, %56 : !quantum.bit, !quantum.bit
      %57 = quantum.extract %0[ 56] : !quantum.reg -> !quantum.bit
      %out_qubits_55:2 = quantum.custom "CNOT"() %out_qubits_54#0, %57 : !quantum.bit, !quantum.bit
      %58 = quantum.extract %0[ 57] : !quantum.reg -> !quantum.bit
      %out_qubits_56:2 = quantum.custom "CNOT"() %out_qubits_55#0, %58 : !quantum.bit, !quantum.bit
      %59 = quantum.extract %0[ 58] : !quantum.reg -> !quantum.bit
      %out_qubits_57:2 = quantum.custom "CNOT"() %out_qubits_56#0, %59 : !quantum.bit, !quantum.bit
      %60 = quantum.extract %0[ 59] : !quantum.reg -> !quantum.bit
      %out_qubits_58:2 = quantum.custom "CNOT"() %out_qubits_57#0, %60 : !quantum.bit, !quantum.bit
      %61 = quantum.extract %0[ 60] : !quantum.reg -> !quantum.bit
      %out_qubits_59:2 = quantum.custom "CNOT"() %out_qubits_58#0, %61 : !quantum.bit, !quantum.bit
      %62 = quantum.extract %0[ 61] : !quantum.reg -> !quantum.bit
      %out_qubits_60:2 = quantum.custom "CNOT"() %out_qubits_59#0, %62 : !quantum.bit, !quantum.bit
      %63 = quantum.extract %0[ 62] : !quantum.reg -> !quantum.bit
      %out_qubits_61:2 = quantum.custom "CNOT"() %out_qubits_60#0, %63 : !quantum.bit, !quantum.bit
      %64 = quantum.extract %0[ 63] : !quantum.reg -> !quantum.bit
      %out_qubits_62:2 = quantum.custom "CNOT"() %out_qubits_61#0, %64 : !quantum.bit, !quantum.bit
      %65 = quantum.extract %0[ 64] : !quantum.reg -> !quantum.bit
      %out_qubits_63:2 = quantum.custom "CNOT"() %out_qubits_62#0, %65 : !quantum.bit, !quantum.bit
      %66 = quantum.extract %0[ 65] : !quantum.reg -> !quantum.bit
      %out_qubits_64:2 = quantum.custom "CNOT"() %out_qubits_63#0, %66 : !quantum.bit, !quantum.bit
      %67 = quantum.extract %0[ 66] : !quantum.reg -> !quantum.bit
      %out_qubits_65:2 = quantum.custom "CNOT"() %out_qubits_64#0, %67 : !quantum.bit, !quantum.bit
      %68 = quantum.extract %0[ 67] : !quantum.reg -> !quantum.bit
      %out_qubits_66:2 = quantum.custom "CNOT"() %out_qubits_65#0, %68 : !quantum.bit, !quantum.bit
      %69 = quantum.extract %0[ 68] : !quantum.reg -> !quantum.bit
      %out_qubits_67:2 = quantum.custom "CNOT"() %out_qubits_66#0, %69 : !quantum.bit, !quantum.bit
      %70 = quantum.extract %0[ 69] : !quantum.reg -> !quantum.bit
      %out_qubits_68:2 = quantum.custom "CNOT"() %out_qubits_67#0, %70 : !quantum.bit, !quantum.bit
      %mres, %out_qubit = quantum.measure %out_qubits_68#0 : i1, !quantum.bit
      %from_elements = tensor.from_elements %mres : tensor<i1>
      %mres_69, %out_qubit_70 = quantum.measure %out_qubits_0#1 : i1, !quantum.bit
      %from_elements_71 = tensor.from_elements %mres_69 : tensor<i1>
      %mres_72, %out_qubit_73 = quantum.measure %out_qubits_1#1 : i1, !quantum.bit
      %from_elements_74 = tensor.from_elements %mres_72 : tensor<i1>
      %mres_75, %out_qubit_76 = quantum.measure %out_qubits_2#1 : i1, !quantum.bit
      %from_elements_77 = tensor.from_elements %mres_75 : tensor<i1>
      %mres_78, %out_qubit_79 = quantum.measure %out_qubits_3#1 : i1, !quantum.bit
      %from_elements_80 = tensor.from_elements %mres_78 : tensor<i1>
      %mres_81, %out_qubit_82 = quantum.measure %out_qubits_4#1 : i1, !quantum.bit
      %from_elements_83 = tensor.from_elements %mres_81 : tensor<i1>
      %mres_84, %out_qubit_85 = quantum.measure %out_qubits_5#1 : i1, !quantum.bit
      %from_elements_86 = tensor.from_elements %mres_84 : tensor<i1>
      %mres_87, %out_qubit_88 = quantum.measure %out_qubits_6#1 : i1, !quantum.bit
      %from_elements_89 = tensor.from_elements %mres_87 : tensor<i1>
      %mres_90, %out_qubit_91 = quantum.measure %out_qubits_7#1 : i1, !quantum.bit
      %from_elements_92 = tensor.from_elements %mres_90 : tensor<i1>
      %mres_93, %out_qubit_94 = quantum.measure %out_qubits_8#1 : i1, !quantum.bit
      %from_elements_95 = tensor.from_elements %mres_93 : tensor<i1>
      %mres_96, %out_qubit_97 = quantum.measure %out_qubits_9#1 : i1, !quantum.bit
      %from_elements_98 = tensor.from_elements %mres_96 : tensor<i1>
      %mres_99, %out_qubit_100 = quantum.measure %out_qubits_10#1 : i1, !quantum.bit
      %from_elements_101 = tensor.from_elements %mres_99 : tensor<i1>
      %mres_102, %out_qubit_103 = quantum.measure %out_qubits_11#1 : i1, !quantum.bit
      %from_elements_104 = tensor.from_elements %mres_102 : tensor<i1>
      %mres_105, %out_qubit_106 = quantum.measure %out_qubits_12#1 : i1, !quantum.bit
      %from_elements_107 = tensor.from_elements %mres_105 : tensor<i1>
      %mres_108, %out_qubit_109 = quantum.measure %out_qubits_13#1 : i1, !quantum.bit
      %from_elements_110 = tensor.from_elements %mres_108 : tensor<i1>
      %mres_111, %out_qubit_112 = quantum.measure %out_qubits_14#1 : i1, !quantum.bit
      %from_elements_113 = tensor.from_elements %mres_111 : tensor<i1>
      %mres_114, %out_qubit_115 = quantum.measure %out_qubits_15#1 : i1, !quantum.bit
      %from_elements_116 = tensor.from_elements %mres_114 : tensor<i1>
      %mres_117, %out_qubit_118 = quantum.measure %out_qubits_16#1 : i1, !quantum.bit
      %from_elements_119 = tensor.from_elements %mres_117 : tensor<i1>
      %mres_120, %out_qubit_121 = quantum.measure %out_qubits_17#1 : i1, !quantum.bit
      %from_elements_122 = tensor.from_elements %mres_120 : tensor<i1>
      %mres_123, %out_qubit_124 = quantum.measure %out_qubits_18#1 : i1, !quantum.bit
      %from_elements_125 = tensor.from_elements %mres_123 : tensor<i1>
      %mres_126, %out_qubit_127 = quantum.measure %out_qubits_19#1 : i1, !quantum.bit
      %from_elements_128 = tensor.from_elements %mres_126 : tensor<i1>
      %mres_129, %out_qubit_130 = quantum.measure %out_qubits_20#1 : i1, !quantum.bit
      %from_elements_131 = tensor.from_elements %mres_129 : tensor<i1>
      %mres_132, %out_qubit_133 = quantum.measure %out_qubits_21#1 : i1, !quantum.bit
      %from_elements_134 = tensor.from_elements %mres_132 : tensor<i1>
      %mres_135, %out_qubit_136 = quantum.measure %out_qubits_22#1 : i1, !quantum.bit
      %from_elements_137 = tensor.from_elements %mres_135 : tensor<i1>
      %mres_138, %out_qubit_139 = quantum.measure %out_qubits_23#1 : i1, !quantum.bit
      %from_elements_140 = tensor.from_elements %mres_138 : tensor<i1>
      %mres_141, %out_qubit_142 = quantum.measure %out_qubits_24#1 : i1, !quantum.bit
      %from_elements_143 = tensor.from_elements %mres_141 : tensor<i1>
      %mres_144, %out_qubit_145 = quantum.measure %out_qubits_25#1 : i1, !quantum.bit
      %from_elements_146 = tensor.from_elements %mres_144 : tensor<i1>
      %mres_147, %out_qubit_148 = quantum.measure %out_qubits_26#1 : i1, !quantum.bit
      %from_elements_149 = tensor.from_elements %mres_147 : tensor<i1>
      %mres_150, %out_qubit_151 = quantum.measure %out_qubits_27#1 : i1, !quantum.bit
      %from_elements_152 = tensor.from_elements %mres_150 : tensor<i1>
      %mres_153, %out_qubit_154 = quantum.measure %out_qubits_28#1 : i1, !quantum.bit
      %from_elements_155 = tensor.from_elements %mres_153 : tensor<i1>
      %mres_156, %out_qubit_157 = quantum.measure %out_qubits_29#1 : i1, !quantum.bit
      %from_elements_158 = tensor.from_elements %mres_156 : tensor<i1>
      %mres_159, %out_qubit_160 = quantum.measure %out_qubits_30#1 : i1, !quantum.bit
      %from_elements_161 = tensor.from_elements %mres_159 : tensor<i1>
      %mres_162, %out_qubit_163 = quantum.measure %out_qubits_31#1 : i1, !quantum.bit
      %from_elements_164 = tensor.from_elements %mres_162 : tensor<i1>
      %mres_165, %out_qubit_166 = quantum.measure %out_qubits_32#1 : i1, !quantum.bit
      %from_elements_167 = tensor.from_elements %mres_165 : tensor<i1>
      %mres_168, %out_qubit_169 = quantum.measure %out_qubits_33#1 : i1, !quantum.bit
      %from_elements_170 = tensor.from_elements %mres_168 : tensor<i1>
      %mres_171, %out_qubit_172 = quantum.measure %out_qubits_34#1 : i1, !quantum.bit
      %from_elements_173 = tensor.from_elements %mres_171 : tensor<i1>
      %mres_174, %out_qubit_175 = quantum.measure %out_qubits_35#1 : i1, !quantum.bit
      %from_elements_176 = tensor.from_elements %mres_174 : tensor<i1>
      %mres_177, %out_qubit_178 = quantum.measure %out_qubits_36#1 : i1, !quantum.bit
      %from_elements_179 = tensor.from_elements %mres_177 : tensor<i1>
      %mres_180, %out_qubit_181 = quantum.measure %out_qubits_37#1 : i1, !quantum.bit
      %from_elements_182 = tensor.from_elements %mres_180 : tensor<i1>
      %mres_183, %out_qubit_184 = quantum.measure %out_qubits_38#1 : i1, !quantum.bit
      %from_elements_185 = tensor.from_elements %mres_183 : tensor<i1>
      %mres_186, %out_qubit_187 = quantum.measure %out_qubits_39#1 : i1, !quantum.bit
      %from_elements_188 = tensor.from_elements %mres_186 : tensor<i1>
      %mres_189, %out_qubit_190 = quantum.measure %out_qubits_40#1 : i1, !quantum.bit
      %from_elements_191 = tensor.from_elements %mres_189 : tensor<i1>
      %mres_192, %out_qubit_193 = quantum.measure %out_qubits_41#1 : i1, !quantum.bit
      %from_elements_194 = tensor.from_elements %mres_192 : tensor<i1>
      %mres_195, %out_qubit_196 = quantum.measure %out_qubits_42#1 : i1, !quantum.bit
      %from_elements_197 = tensor.from_elements %mres_195 : tensor<i1>
      %mres_198, %out_qubit_199 = quantum.measure %out_qubits_43#1 : i1, !quantum.bit
      %from_elements_200 = tensor.from_elements %mres_198 : tensor<i1>
      %mres_201, %out_qubit_202 = quantum.measure %out_qubits_44#1 : i1, !quantum.bit
      %from_elements_203 = tensor.from_elements %mres_201 : tensor<i1>
      %mres_204, %out_qubit_205 = quantum.measure %out_qubits_45#1 : i1, !quantum.bit
      %from_elements_206 = tensor.from_elements %mres_204 : tensor<i1>
      %mres_207, %out_qubit_208 = quantum.measure %out_qubits_46#1 : i1, !quantum.bit
      %from_elements_209 = tensor.from_elements %mres_207 : tensor<i1>
      %mres_210, %out_qubit_211 = quantum.measure %out_qubits_47#1 : i1, !quantum.bit
      %from_elements_212 = tensor.from_elements %mres_210 : tensor<i1>
      %mres_213, %out_qubit_214 = quantum.measure %out_qubits_48#1 : i1, !quantum.bit
      %from_elements_215 = tensor.from_elements %mres_213 : tensor<i1>
      %mres_216, %out_qubit_217 = quantum.measure %out_qubits_49#1 : i1, !quantum.bit
      %from_elements_218 = tensor.from_elements %mres_216 : tensor<i1>
      %mres_219, %out_qubit_220 = quantum.measure %out_qubits_50#1 : i1, !quantum.bit
      %from_elements_221 = tensor.from_elements %mres_219 : tensor<i1>
      %mres_222, %out_qubit_223 = quantum.measure %out_qubits_51#1 : i1, !quantum.bit
      %from_elements_224 = tensor.from_elements %mres_222 : tensor<i1>
      %mres_225, %out_qubit_226 = quantum.measure %out_qubits_52#1 : i1, !quantum.bit
      %from_elements_227 = tensor.from_elements %mres_225 : tensor<i1>
      %mres_228, %out_qubit_229 = quantum.measure %out_qubits_53#1 : i1, !quantum.bit
      %from_elements_230 = tensor.from_elements %mres_228 : tensor<i1>
      %mres_231, %out_qubit_232 = quantum.measure %out_qubits_54#1 : i1, !quantum.bit
      %from_elements_233 = tensor.from_elements %mres_231 : tensor<i1>
      %mres_234, %out_qubit_235 = quantum.measure %out_qubits_55#1 : i1, !quantum.bit
      %from_elements_236 = tensor.from_elements %mres_234 : tensor<i1>
      %mres_237, %out_qubit_238 = quantum.measure %out_qubits_56#1 : i1, !quantum.bit
      %from_elements_239 = tensor.from_elements %mres_237 : tensor<i1>
      %mres_240, %out_qubit_241 = quantum.measure %out_qubits_57#1 : i1, !quantum.bit
      %from_elements_242 = tensor.from_elements %mres_240 : tensor<i1>
      %mres_243, %out_qubit_244 = quantum.measure %out_qubits_58#1 : i1, !quantum.bit
      %from_elements_245 = tensor.from_elements %mres_243 : tensor<i1>
      %mres_246, %out_qubit_247 = quantum.measure %out_qubits_59#1 : i1, !quantum.bit
      %from_elements_248 = tensor.from_elements %mres_246 : tensor<i1>
      %mres_249, %out_qubit_250 = quantum.measure %out_qubits_60#1 : i1, !quantum.bit
      %from_elements_251 = tensor.from_elements %mres_249 : tensor<i1>
      %mres_252, %out_qubit_253 = quantum.measure %out_qubits_61#1 : i1, !quantum.bit
      %from_elements_254 = tensor.from_elements %mres_252 : tensor<i1>
      %mres_255, %out_qubit_256 = quantum.measure %out_qubits_62#1 : i1, !quantum.bit
      %from_elements_257 = tensor.from_elements %mres_255 : tensor<i1>
      %mres_258, %out_qubit_259 = quantum.measure %out_qubits_63#1 : i1, !quantum.bit
      %from_elements_260 = tensor.from_elements %mres_258 : tensor<i1>
      %mres_261, %out_qubit_262 = quantum.measure %out_qubits_64#1 : i1, !quantum.bit
      %from_elements_263 = tensor.from_elements %mres_261 : tensor<i1>
      %mres_264, %out_qubit_265 = quantum.measure %out_qubits_65#1 : i1, !quantum.bit
      %from_elements_266 = tensor.from_elements %mres_264 : tensor<i1>
      %mres_267, %out_qubit_268 = quantum.measure %out_qubits_66#1 : i1, !quantum.bit
      %from_elements_269 = tensor.from_elements %mres_267 : tensor<i1>
      %mres_270, %out_qubit_271 = quantum.measure %out_qubits_67#1 : i1, !quantum.bit
      %from_elements_272 = tensor.from_elements %mres_270 : tensor<i1>
      %mres_273, %out_qubit_274 = quantum.measure %out_qubits_68#1 : i1, !quantum.bit
      %from_elements_275 = tensor.from_elements %mres_273 : tensor<i1>
      %71 = quantum.insert %0[ 0], %out_qubit : !quantum.reg, !quantum.bit
      %72 = quantum.insert %71[ 1], %out_qubit_70 : !quantum.reg, !quantum.bit
      %73 = quantum.insert %72[ 2], %out_qubit_73 : !quantum.reg, !quantum.bit
      %74 = quantum.insert %73[ 3], %out_qubit_76 : !quantum.reg, !quantum.bit
      %75 = quantum.insert %74[ 4], %out_qubit_79 : !quantum.reg, !quantum.bit
      %76 = quantum.insert %75[ 5], %out_qubit_82 : !quantum.reg, !quantum.bit
      %77 = quantum.insert %76[ 6], %out_qubit_85 : !quantum.reg, !quantum.bit
      %78 = quantum.insert %77[ 7], %out_qubit_88 : !quantum.reg, !quantum.bit
      %79 = quantum.insert %78[ 8], %out_qubit_91 : !quantum.reg, !quantum.bit
      %80 = quantum.insert %79[ 9], %out_qubit_94 : !quantum.reg, !quantum.bit
      %81 = quantum.insert %80[ 10], %out_qubit_97 : !quantum.reg, !quantum.bit
      %82 = quantum.insert %81[ 11], %out_qubit_100 : !quantum.reg, !quantum.bit
      %83 = quantum.insert %82[ 12], %out_qubit_103 : !quantum.reg, !quantum.bit
      %84 = quantum.insert %83[ 13], %out_qubit_106 : !quantum.reg, !quantum.bit
      %85 = quantum.insert %84[ 14], %out_qubit_109 : !quantum.reg, !quantum.bit
      %86 = quantum.insert %85[ 15], %out_qubit_112 : !quantum.reg, !quantum.bit
      %87 = quantum.insert %86[ 16], %out_qubit_115 : !quantum.reg, !quantum.bit
      %88 = quantum.insert %87[ 17], %out_qubit_118 : !quantum.reg, !quantum.bit
      %89 = quantum.insert %88[ 18], %out_qubit_121 : !quantum.reg, !quantum.bit
      %90 = quantum.insert %89[ 19], %out_qubit_124 : !quantum.reg, !quantum.bit
      %91 = quantum.insert %90[ 20], %out_qubit_127 : !quantum.reg, !quantum.bit
      %92 = quantum.insert %91[ 21], %out_qubit_130 : !quantum.reg, !quantum.bit
      %93 = quantum.insert %92[ 22], %out_qubit_133 : !quantum.reg, !quantum.bit
      %94 = quantum.insert %93[ 23], %out_qubit_136 : !quantum.reg, !quantum.bit
      %95 = quantum.insert %94[ 24], %out_qubit_139 : !quantum.reg, !quantum.bit
      %96 = quantum.insert %95[ 25], %out_qubit_142 : !quantum.reg, !quantum.bit
      %97 = quantum.insert %96[ 26], %out_qubit_145 : !quantum.reg, !quantum.bit
      %98 = quantum.insert %97[ 27], %out_qubit_148 : !quantum.reg, !quantum.bit
      %99 = quantum.insert %98[ 28], %out_qubit_151 : !quantum.reg, !quantum.bit
      %100 = quantum.insert %99[ 29], %out_qubit_154 : !quantum.reg, !quantum.bit
      %101 = quantum.insert %100[ 30], %out_qubit_157 : !quantum.reg, !quantum.bit
      %102 = quantum.insert %101[ 31], %out_qubit_160 : !quantum.reg, !quantum.bit
      %103 = quantum.insert %102[ 32], %out_qubit_163 : !quantum.reg, !quantum.bit
      %104 = quantum.insert %103[ 33], %out_qubit_166 : !quantum.reg, !quantum.bit
      %105 = quantum.insert %104[ 34], %out_qubit_169 : !quantum.reg, !quantum.bit
      %106 = quantum.insert %105[ 35], %out_qubit_172 : !quantum.reg, !quantum.bit
      %107 = quantum.insert %106[ 36], %out_qubit_175 : !quantum.reg, !quantum.bit
      %108 = quantum.insert %107[ 37], %out_qubit_178 : !quantum.reg, !quantum.bit
      %109 = quantum.insert %108[ 38], %out_qubit_181 : !quantum.reg, !quantum.bit
      %110 = quantum.insert %109[ 39], %out_qubit_184 : !quantum.reg, !quantum.bit
      %111 = quantum.insert %110[ 40], %out_qubit_187 : !quantum.reg, !quantum.bit
      %112 = quantum.insert %111[ 41], %out_qubit_190 : !quantum.reg, !quantum.bit
      %113 = quantum.insert %112[ 42], %out_qubit_193 : !quantum.reg, !quantum.bit
      %114 = quantum.insert %113[ 43], %out_qubit_196 : !quantum.reg, !quantum.bit
      %115 = quantum.insert %114[ 44], %out_qubit_199 : !quantum.reg, !quantum.bit
      %116 = quantum.insert %115[ 45], %out_qubit_202 : !quantum.reg, !quantum.bit
      %117 = quantum.insert %116[ 46], %out_qubit_205 : !quantum.reg, !quantum.bit
      %118 = quantum.insert %117[ 47], %out_qubit_208 : !quantum.reg, !quantum.bit
      %119 = quantum.insert %118[ 48], %out_qubit_211 : !quantum.reg, !quantum.bit
      %120 = quantum.insert %119[ 49], %out_qubit_214 : !quantum.reg, !quantum.bit
      %121 = quantum.insert %120[ 50], %out_qubit_217 : !quantum.reg, !quantum.bit
      %122 = quantum.insert %121[ 51], %out_qubit_220 : !quantum.reg, !quantum.bit
      %123 = quantum.insert %122[ 52], %out_qubit_223 : !quantum.reg, !quantum.bit
      %124 = quantum.insert %123[ 53], %out_qubit_226 : !quantum.reg, !quantum.bit
      %125 = quantum.insert %124[ 54], %out_qubit_229 : !quantum.reg, !quantum.bit
      %126 = quantum.insert %125[ 55], %out_qubit_232 : !quantum.reg, !quantum.bit
      %127 = quantum.insert %126[ 56], %out_qubit_235 : !quantum.reg, !quantum.bit
      %128 = quantum.insert %127[ 57], %out_qubit_238 : !quantum.reg, !quantum.bit
      %129 = quantum.insert %128[ 58], %out_qubit_241 : !quantum.reg, !quantum.bit
      %130 = quantum.insert %129[ 59], %out_qubit_244 : !quantum.reg, !quantum.bit
      %131 = quantum.insert %130[ 60], %out_qubit_247 : !quantum.reg, !quantum.bit
      %132 = quantum.insert %131[ 61], %out_qubit_250 : !quantum.reg, !quantum.bit
      %133 = quantum.insert %132[ 62], %out_qubit_253 : !quantum.reg, !quantum.bit
      %134 = quantum.insert %133[ 63], %out_qubit_256 : !quantum.reg, !quantum.bit
      %135 = quantum.insert %134[ 64], %out_qubit_259 : !quantum.reg, !quantum.bit
      %136 = quantum.insert %135[ 65], %out_qubit_262 : !quantum.reg, !quantum.bit
      %137 = quantum.insert %136[ 66], %out_qubit_265 : !quantum.reg, !quantum.bit
      %138 = quantum.insert %137[ 67], %out_qubit_268 : !quantum.reg, !quantum.bit
      %139 = quantum.insert %138[ 68], %out_qubit_271 : !quantum.reg, !quantum.bit
      %140 = quantum.insert %139[ 69], %out_qubit_274 : !quantum.reg, !quantum.bit
      quantum.dealloc %140 : !quantum.reg
      quantum.device_release
      return %from_elements, %from_elements_71, %from_elements_74, %from_elements_77, %from_elements_80, %from_elements_83, %from_elements_86, %from_elements_89, %from_elements_92, %from_elements_95, %from_elements_98, %from_elements_101, %from_elements_104, %from_elements_107, %from_elements_110, %from_elements_113, %from_elements_116, %from_elements_119, %from_elements_122, %from_elements_125, %from_elements_128, %from_elements_131, %from_elements_134, %from_elements_137, %from_elements_140, %from_elements_143, %from_elements_146, %from_elements_149, %from_elements_152, %from_elements_155, %from_elements_158, %from_elements_161, %from_elements_164, %from_elements_167, %from_elements_170, %from_elements_173, %from_elements_176, %from_elements_179, %from_elements_182, %from_elements_185, %from_elements_188, %from_elements_191, %from_elements_194, %from_elements_197, %from_elements_200, %from_elements_203, %from_elements_206, %from_elements_209, %from_elements_212, %from_elements_215, %from_elements_218, %from_elements_221, %from_elements_224, %from_elements_227, %from_elements_230, %from_elements_233, %from_elements_236, %from_elements_239, %from_elements_242, %from_elements_245, %from_elements_248, %from_elements_251, %from_elements_254, %from_elements_257, %from_elements_260, %from_elements_263, %from_elements_266, %from_elements_269, %from_elements_272, %from_elements_275 : tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>, tensor<i1>
    }
  }
  func.func @setup() {
    quantum.init
    return
  }
  func.func @teardown() {
    quantum.finalize
    return
  }
}