module attributes {quake.mangled_name_map = {__nvqpp__mlirgen____nvqppBuilderKernel_DUD4OSRWC2 = "__nvqpp__mlirgen____nvqppBuilderKernel_DUD4OSRWC2_PyKernelEntryPointRewrite"}} {
  func.func @__nvqpp__mlirgen____nvqppBuilderKernel_DUD4OSRWC2() attributes {"cudaq-entrypoint", "cudaq-kernel"} {
    %cst = arith.constant 0.012271846303085129 : f64
    %cst_0 = arith.constant 0.024543692606170259 : f64
    %cst_1 = arith.constant -0.024543692606170259 : f64
    %cst_2 = arith.constant 0.049087385212340517 : f64
    %cst_3 = arith.constant 0.098174770424681035 : f64
    %cst_4 = arith.constant 0.19634954084936207 : f64
    %cst_5 = arith.constant 0.39269908169872414 : f64
    %cst_6 = arith.constant 0.78539816339744828 : f64
    %cst_7 = arith.constant -0.012271846303085129 : f64
    %cst_8 = arith.constant -0.78539816339744828 : f64
    %cst_9 = arith.constant -0.049087385212340517 : f64
    %cst_10 = arith.constant -0.39269908169872414 : f64
    %cst_11 = arith.constant -0.098174770424681035 : f64
    %cst_12 = arith.constant -0.19634954084936207 : f64
    %0 = quake.alloca !quake.veq<12>
    %1 = quake.extract_ref %0[0] : (!quake.veq<12>) -> !quake.ref
    quake.h %1 : (!quake.ref) -> ()
    %2 = quake.extract_ref %0[1] : (!quake.veq<12>) -> !quake.ref
    quake.h %2 : (!quake.ref) -> ()
    %3 = quake.extract_ref %0[2] : (!quake.veq<12>) -> !quake.ref
    quake.h %3 : (!quake.ref) -> ()
    %4 = quake.extract_ref %0[3] : (!quake.veq<12>) -> !quake.ref
    quake.h %4 : (!quake.ref) -> ()
    %5 = quake.extract_ref %0[4] : (!quake.veq<12>) -> !quake.ref
    quake.h %5 : (!quake.ref) -> ()
    quake.x [%4] %5 : (!quake.ref, !quake.ref) -> ()
    quake.x [%5] %4 : (!quake.ref, !quake.ref) -> ()
    quake.x [%4] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_12) %4 : (f64, !quake.ref) -> ()
    quake.rz (%cst_11) %5 : (f64, !quake.ref) -> ()
    %6 = quake.extract_ref %0[5] : (!quake.veq<12>) -> !quake.ref
    quake.h %6 : (!quake.ref) -> ()
    quake.x [%3] %6 : (!quake.ref, !quake.ref) -> ()
    quake.x [%6] %3 : (!quake.ref, !quake.ref) -> ()
    quake.x [%3] %6 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %3 : (f64, !quake.ref) -> ()
    quake.rz (%cst_9) %6 : (f64, !quake.ref) -> ()
    %7 = quake.extract_ref %0[6] : (!quake.veq<12>) -> !quake.ref
    quake.h %7 : (!quake.ref) -> ()
    %8 = quake.extract_ref %0[7] : (!quake.veq<12>) -> !quake.ref
    quake.h %8 : (!quake.ref) -> ()
    %9 = quake.extract_ref %0[8] : (!quake.veq<12>) -> !quake.ref
    quake.x %9 : (!quake.ref) -> ()
    %10 = quake.extract_ref %0[11] : (!quake.veq<12>) -> !quake.ref
    quake.h %10 : (!quake.ref) -> ()
    %11 = quake.extract_ref %0[10] : (!quake.veq<12>) -> !quake.ref
    quake.x [%11] %10 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%1] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.x [%11] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%1] %10 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.h %10 : (!quake.ref) -> ()
    quake.x [%10] %11 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%10] %11 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.x [%1] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%1] %10 : (!quake.ref, !quake.ref) -> ()
    quake.h %10 : (!quake.ref) -> ()
    quake.x [%11] %10 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%1] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.x [%11] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%1] %10 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    %12 = quake.extract_ref %0[9] : (!quake.veq<12>) -> !quake.ref
    quake.x [%12] %11 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%12] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.x [%11] %12 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.x [%11] %12 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.x [%12] %11 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%12] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%1] %11 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.x [%9] %12 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.x [%9] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%1] %9 : (!quake.ref, !quake.ref) -> ()
    quake.h %9 : (!quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.x [%12] %9 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%1] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.x [%12] %9 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%1] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.h %9 : (!quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.x [%9] %12 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.x [%9] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%1] %12 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %1 : (!quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%1] %9 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %8 : (!quake.ref, !quake.ref) -> ()
    quake.x [%8] %1 : (!quake.ref, !quake.ref) -> ()
    quake.x [%1] %8 : (!quake.ref, !quake.ref) -> ()
    quake.h %1 : (!quake.ref) -> ()
    quake.rz (%cst_7) %8 : (f64, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.rz (%cst_6) %11 : (f64, !quake.ref) -> ()
    quake.x [%9] %11 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%2] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%9] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%2] %11 : (!quake.ref, !quake.ref) -> ()
    quake.x [%2] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %2 : (!quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%2] %9 : (!quake.ref, !quake.ref) -> ()
    quake.h %9 : (!quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.x [%11] %9 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%2] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.x [%11] %9 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%2] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.h %9 : (!quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%2] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %2 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%2] %11 : (!quake.ref, !quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.x [%9] %11 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%2] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.x [%9] %11 : (!quake.ref, !quake.ref) -> ()
    quake.t %9 : (!quake.ref) -> ()
    quake.rz (%cst_8) %11 : (f64, !quake.ref) -> ()
    quake.x [%2] %11 : (!quake.ref, !quake.ref) -> ()
    quake.x [%2] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %2 : (!quake.ref) -> ()
    quake.rz (%cst_8) %9 : (f64, !quake.ref) -> ()
    quake.x [%2] %9 : (!quake.ref, !quake.ref) -> ()
    quake.t %11 : (!quake.ref) -> ()
    quake.h %11 : (!quake.ref) -> ()
    quake.rz (%cst_6) %10 : (f64, !quake.ref) -> ()
    quake.x [%12] %10 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%2] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.x [%12] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%2] %10 : (!quake.ref, !quake.ref) -> ()
    quake.x [%2] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %2 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%2] %12 : (!quake.ref, !quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.h %10 : (!quake.ref) -> ()
    quake.x [%10] %12 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%2] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.x [%10] %12 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%2] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.h %12 : (!quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.x [%2] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %2 : (!quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%2] %10 : (!quake.ref, !quake.ref) -> ()
    quake.h %10 : (!quake.ref) -> ()
    quake.x [%12] %10 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%2] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.x [%12] %10 : (!quake.ref, !quake.ref) -> ()
    quake.t %12 : (!quake.ref) -> ()
    quake.rz (%cst_8) %10 : (f64, !quake.ref) -> ()
    quake.x [%2] %10 : (!quake.ref, !quake.ref) -> ()
    quake.x [%2] %12 : (!quake.ref, !quake.ref) -> ()
    quake.t %2 : (!quake.ref) -> ()
    quake.rz (%cst_8) %12 : (f64, !quake.ref) -> ()
    quake.x [%2] %12 : (!quake.ref, !quake.ref) -> ()
    quake.x [%2] %7 : (!quake.ref, !quake.ref) -> ()
    quake.x [%7] %2 : (!quake.ref, !quake.ref) -> ()
    quake.x [%2] %7 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %2 : (f64, !quake.ref) -> ()
    quake.x [%2] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %1 : (f64, !quake.ref) -> ()
    quake.x [%2] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %1 : (f64, !quake.ref) -> ()
    quake.h %2 : (!quake.ref) -> ()
    quake.x [%3] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_5) %1 : (f64, !quake.ref) -> ()
    quake.x [%3] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %1 : (f64, !quake.ref) -> ()
    quake.rz (%cst_8) %3 : (f64, !quake.ref) -> ()
    quake.x [%3] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %2 : (f64, !quake.ref) -> ()
    quake.x [%3] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %2 : (f64, !quake.ref) -> ()
    quake.h %3 : (!quake.ref) -> ()
    quake.x [%4] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_4) %1 : (f64, !quake.ref) -> ()
    quake.x [%4] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_12) %1 : (f64, !quake.ref) -> ()
    quake.rz (%cst_10) %4 : (f64, !quake.ref) -> ()
    quake.x [%4] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_5) %2 : (f64, !quake.ref) -> ()
    quake.x [%4] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %2 : (f64, !quake.ref) -> ()
    quake.rz (%cst_8) %4 : (f64, !quake.ref) -> ()
    quake.x [%4] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %3 : (f64, !quake.ref) -> ()
    quake.x [%4] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %3 : (f64, !quake.ref) -> ()
    quake.h %4 : (!quake.ref) -> ()
    quake.x [%5] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_3) %1 : (f64, !quake.ref) -> ()
    quake.x [%5] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_11) %1 : (f64, !quake.ref) -> ()
    quake.rz (%cst_12) %5 : (f64, !quake.ref) -> ()
    quake.x [%5] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_4) %2 : (f64, !quake.ref) -> ()
    quake.x [%5] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_12) %2 : (f64, !quake.ref) -> ()
    quake.rz (%cst_10) %5 : (f64, !quake.ref) -> ()
    quake.x [%5] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_5) %3 : (f64, !quake.ref) -> ()
    quake.x [%5] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %3 : (f64, !quake.ref) -> ()
    quake.rz (%cst_8) %5 : (f64, !quake.ref) -> ()
    quake.x [%5] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %4 : (f64, !quake.ref) -> ()
    quake.x [%5] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %4 : (f64, !quake.ref) -> ()
    quake.h %5 : (!quake.ref) -> ()
    quake.x [%6] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_2) %1 : (f64, !quake.ref) -> ()
    quake.x [%6] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_9) %1 : (f64, !quake.ref) -> ()
    quake.rz (%cst_11) %6 : (f64, !quake.ref) -> ()
    quake.x [%6] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_3) %2 : (f64, !quake.ref) -> ()
    quake.x [%6] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_11) %2 : (f64, !quake.ref) -> ()
    quake.rz (%cst_12) %6 : (f64, !quake.ref) -> ()
    quake.x [%6] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_4) %3 : (f64, !quake.ref) -> ()
    quake.x [%6] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_12) %3 : (f64, !quake.ref) -> ()
    quake.rz (%cst_10) %6 : (f64, !quake.ref) -> ()
    quake.x [%6] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_5) %4 : (f64, !quake.ref) -> ()
    quake.x [%6] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %4 : (f64, !quake.ref) -> ()
    quake.rz (%cst_8) %6 : (f64, !quake.ref) -> ()
    quake.x [%6] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %5 : (f64, !quake.ref) -> ()
    quake.x [%6] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %5 : (f64, !quake.ref) -> ()
    quake.h %6 : (!quake.ref) -> ()
    quake.rz (%cst_1) %7 : (f64, !quake.ref) -> ()
    quake.x [%7] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_0) %1 : (f64, !quake.ref) -> ()
    quake.x [%7] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_1) %1 : (f64, !quake.ref) -> ()
    quake.rz (%cst_9) %7 : (f64, !quake.ref) -> ()
    quake.x [%7] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_2) %2 : (f64, !quake.ref) -> ()
    quake.x [%7] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_9) %2 : (f64, !quake.ref) -> ()
    quake.rz (%cst_11) %7 : (f64, !quake.ref) -> ()
    quake.x [%7] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_3) %3 : (f64, !quake.ref) -> ()
    quake.x [%7] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_11) %3 : (f64, !quake.ref) -> ()
    quake.rz (%cst_12) %7 : (f64, !quake.ref) -> ()
    quake.x [%7] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_4) %4 : (f64, !quake.ref) -> ()
    quake.x [%7] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_12) %4 : (f64, !quake.ref) -> ()
    quake.rz (%cst_10) %7 : (f64, !quake.ref) -> ()
    quake.x [%7] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_5) %5 : (f64, !quake.ref) -> ()
    quake.x [%7] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %5 : (f64, !quake.ref) -> ()
    quake.rz (%cst_8) %7 : (f64, !quake.ref) -> ()
    quake.x [%7] %6 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %6 : (f64, !quake.ref) -> ()
    quake.x [%7] %6 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %6 : (f64, !quake.ref) -> ()
    quake.h %7 : (!quake.ref) -> ()
    quake.x [%8] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst) %1 : (f64, !quake.ref) -> ()
    quake.x [%8] %1 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_7) %1 : (f64, !quake.ref) -> ()
    quake.rz (%cst_1) %8 : (f64, !quake.ref) -> ()
    quake.x [%8] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_0) %2 : (f64, !quake.ref) -> ()
    quake.x [%8] %2 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_1) %2 : (f64, !quake.ref) -> ()
    quake.rz (%cst_9) %8 : (f64, !quake.ref) -> ()
    quake.x [%8] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_2) %3 : (f64, !quake.ref) -> ()
    quake.x [%8] %3 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_9) %3 : (f64, !quake.ref) -> ()
    quake.rz (%cst_11) %8 : (f64, !quake.ref) -> ()
    quake.x [%8] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_3) %4 : (f64, !quake.ref) -> ()
    quake.x [%8] %4 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_11) %4 : (f64, !quake.ref) -> ()
    quake.rz (%cst_12) %8 : (f64, !quake.ref) -> ()
    quake.x [%8] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_4) %5 : (f64, !quake.ref) -> ()
    quake.x [%8] %5 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_12) %5 : (f64, !quake.ref) -> ()
    quake.rz (%cst_10) %8 : (f64, !quake.ref) -> ()
    quake.x [%8] %6 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_5) %6 : (f64, !quake.ref) -> ()
    quake.x [%8] %6 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_10) %6 : (f64, !quake.ref) -> ()
    quake.rz (%cst_8) %8 : (f64, !quake.ref) -> ()
    quake.x [%8] %7 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_6) %7 : (f64, !quake.ref) -> ()
    quake.x [%8] %7 : (!quake.ref, !quake.ref) -> ()
    quake.rz (%cst_8) %7 : (f64, !quake.ref) -> ()
    quake.h %8 : (!quake.ref) -> ()
    quake.t %10 : (!quake.ref) -> ()
    quake.h %10 : (!quake.ref) -> ()
    %measOut = quake.mz %0 : (!quake.veq<12>) -> !cc.stdvec<!quake.measure>
    return
  }
}
